apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/creatorId: user-gh9b6
    field.cattle.io/ipAddresses: "null"
    field.cattle.io/targetDnsRecordIds: "null"
    field.cattle.io/targetWorkloadIds: "null"
  creationTimestamp: null
  labels:
    cattle.io/creator: norman
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/creatorId: {}
          f:field.cattle.io/ipAddresses: {}
          f:field.cattle.io/targetDnsRecordIds: {}
          f:field.cattle.io/targetWorkloadIds: {}
        f:labels:
          .: {}
          f:cattle.io/creator: {}
      f:spec:
        f:externalName: {}
        f:ports:
          .: {}
          k:{"port":42,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: Go-http-client
    operation: Update
    time: "2020-08-26T21:42:14Z"
  name: rabbitmq
  selfLink: /api/v1/namespaces/worker/services/rabbitmq
spec:
  externalName: rabbitmq.services.svc.cluster.local
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  sessionAffinity: None
  type: ExternalName
status:
  loadBalancer: {}
