# Generated by Django 3.1.7 on 2021-03-28 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('value', models.TextField(null=True)),
                ('placeholder', models.TextField(null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='form_creator.form')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('value', models.CharField(max_length=100, null=True)),
                ('pattern', models.CharField(max_length=100, null=True)),
                ('placeholder', models.CharField(max_length=100, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tel', to='form_creator.form')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('value', models.CharField(max_length=100, null=True)),
                ('placeholder', models.CharField(max_length=100, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string', to='form_creator.form')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Select',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select', to='form_creator.form')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('value', models.CharField(max_length=300, null=True)),
                ('placeholder', models.CharField(max_length=100, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search', to='form_creator.form')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('value', models.IntegerField(default=0)),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='range', to='form_creator.form')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('value', models.CharField(default=1, max_length=100)),
                ('selected', models.BooleanField(default=False)),
                ('select_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='form_creator.select')),
            ],
        ),
        migrations.CreateModel(
            name='Integer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('value', models.IntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integer', to='form_creator.form')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Checkbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('value', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkbox', to='form_creator.form')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
